### PR TITLE
Revert export options change, fix tests accordingly, fix POD accordingly

### PR DESCRIPTION
**Pull request by genio**
Fix for https://rt.cpan.org/Ticket/Display.html?id=113838

### CODE REVIEW

**Comment by rehsack** [comment]
I think that goes to far - see https://rt.cpan.org/Ticket/Display.html?id=113838

**Comment by genio** [comment]
I'm unable to see that right now as there's been a problem with RT all day.

**Comment by rehsack** [comment]
No worries, noone dies because of that :)

**Comment by genio** [comment]
I prefer the current way as well! :) It's up to you; feel free to close this or use bits and pieces.

**Pull request closed without merging**
